version: "3"
networks: 
  db_net: 
   driver: bridge
   
services:
  php:
    image: php:8.1-apache
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
    networks:
      - db_net
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: PIM_VI
      MYSQL_USER: gustavo
      MYSQL_PASSWORD: "12345678"
    ports:
      - 3306:3306
    networks:
      - db_net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - db_net
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: "1234"
    ports:
      - 8181:80